project:
  type: book

book:
  title: "R-workshops"
  author: "Mehtap Hisarciklilar"
  date: "1/20/2025"
  cover-image: cover.png
  chapters:
    - index.qmd
    
    - part: Seminar 1 (21 January 2025)
      chapters: 
      - intro.qmd
      - basics-of-R.qmd
    - part: Seminar 2 (28 January 2025)
      chapters: 
      - data-management-in-R.qmd
      - importing-data-into-R.qmd
      - introduction-to-regression-analysis.qmd
    - part: Seminar 3 (4 February 2025)
      chapters: 
      - multiple-regression-and-diagnostic-checks.qmd
    - part: Seminar 4 (11 February 2025)
      chapters: 
      - introduction-to-time-series-analysis.qmd
    - part: Seminar 5 (18 February 2025)
      chapters:
      - non-stationarity.qmd
      - cointegration.qmd
    - part: Seminar 6 (25 February 2025)
      chapters: 
      - data-visualisation-ggplot2.qmd
      - introduction-to-panel-data-analysis.qmd
    - part: Seminar 7 and 8 (4 and 11 March 2025)
      chapters:
      - panel-data-models.qmd
      - panel-data-misspecification.qmd
    - part: Seminar 9 (18 March 2025)
      chapters:
      - endogeneity-iv-estimation.qmd
    - part: References
      chapters:
      - references.qmd
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    keep-tex: true
    output-file: pdf-book

editor: visual

