project:
  type: book

book:
  title: "Introduction to R"
  author: "Dr Mehtap Hisarciklilar & Dr Robert Riegler"
  date: "1/20/2025"
  cover-image: cover.png
  chapters:
    - index.qmd
    
    - part: Session 1 Introduction to Data Analysis
      chapters:
      - intro.qmd
      - basics-of-R.qmd
      - importing-data.qmd
      - summary-stats.qmd
      - labelling-variables.qmd
      - plotting-variables.qmd
      - ols-regression.qmd
      - student-activity-1.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    keep-tex: true
    output-file: pdf-book

editor: visual

