project:
  type: book

book:
  title: "Introduction to R"
  author: "Mehtap Hisarciklilar & Robert Riegler"
  date: "1/20/2025"
  cover-image: cover.png
  chapters:
    - index.qmd
    - intro.qmd
    - basics-of-R.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

