project:
  type: book

book:
  title: "Introduction to R"
  author: "Mehtap Hisarciklilar & Robert Riegler"
  date: "1/20/2025"
  cover-image: cover.png
  chapters:
    - index.qmd
    
    - part : Session 1: Introduction to Data Analsysis
    chapters:
    - intro.qmd
    - basics-of-R.qmd
    - importing-data.qmd
    - summary-stats.qmd
    - labelling-variables.qmd
    - plotting-variables.qmd
    - references.qmd

  chapters:
    - index.qmd
    
    - part: Seminar 1 (21 January 2025)
      chapters: 
      - intro.qmd
      - basics-of-R.qmd
    - part: Seminar 2 (28 January 2025)
    
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

