# Student Activity

Work on the following tasks on your own or with a person sitting next to you.

1.  Clear the environment

2.  Create a new project called `birth-weight`. You may do this either through the File menu or the button on the top right center of your screen.

3.  Import the `bweight` Excel data into R.

4.  Below are the labels of the variables. Assign these to each of the correponding variable in data.

    | Variable | Label                                       |
    |----------|---------------------------------------------|
    | bwght    | baby's birth weight, in grams               |
    | mage     | mother's age                                |
    | cigs     | average number of cigarettes smoked per day |
    | male     | dummy variable equal to 1 if baby is a male |

5.  Provide summary statistics for the variables.

6.  Calculate the standard deviation for the `bwght` variable.

7.  Estimate a regression model which explains the `bwght` with the mother's age, smoking behaviour, and the baby's gender.

8.  Using the model you estimated, predict the baby's birth weight for the individuals in the sample.
